### ISSUE TITLE
Provide remote certificate

### ISSUE THREAD

**Issue by josiahwiebe** [ihiroshi27/passgenerator-js#1]
Is there any way I could provide a remote certificate rather than a local filesystem one?

**Comment by ihiroshi27** [comment]
Hi @josiahwiebe 

I'm not sure I understand this correctly about remote certificate.
Do you need to add both appleWWDRCA and signCert as a Buffer instead of a local file right?
If so, I'll get to work on it right away.

**Comment by josiahwiebe** [comment]
Correct! I was thinking I could fetch the file from remote and pass the response. 

My serverless setup doesn't persist filesystem across functions so it's key to be able to store the files in durable (S3) storage.

**Comment by ihiroshi27** [comment]
Hi @josiahwiebe

It has been done in v1.0.6.
Let me know if there are any problems.

:)

**Comment by josiahwiebe** [comment]
Worked perfectly. Thank you!
